version: "3.7"

services:
  web:
    container_name: toolbox-backend
    build: .
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      EXTERNAL_API_URL: https://echo-serv.tbxnet.com
      EXTERNAL_API_SECRET_TOKEN: aSuperSecretKey
